[arq]
arq ansible_host=127.0.0.1 ansible_port=2222 ansible_ssh_private_key_file=/home/ifpb/.vagrant.d/insecure_private_key

[banco_dados]
db ansible_host=127.0.0.1 ansible_port=2203 ansible_ssh_private_key_file=/home/ifpb/.vagrant.d/insecure_private_key

[aplicacao]
app ansible_host=127.0.0.1 ansible_port=2204 ansible_ssh_private_key_file=/home/ifpb/.vagrant.d/insecure_private_key

[clientes]
cli ansible_host=127.0.0.1 ansible_port=2205 ansible_ssh_private_key_file=/home/ifpb/.vagrant.d/insecure_private_key

[servidores:children]
arq
banco_dados
aplicacao
clientes

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args="-o StrictHostKeyChecking=no"
