[arq]
arq ansible_host=127.0.0.1 ansible_port=2222 ansible_user=vagrant ansible_ssh_private_key_file=/home/ifpb/.vagrant.d/insecure_private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[banco_dados]
db ansible_host=127.0.0.1 ansible_port=2200 ansible_user=vagrant ansible_ssh_private_key_file=/home/ifpb/.vagrant.d/insecure_private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[aplicacao]
app ansible_host=127.0.0.1 ansible_port=2201 ansible_user=vagrant ansible_ssh_private_key_file=/home/ifpb/.vagrant.d/insecure_private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[clientes]
cli ansible_host=127.0.0.1 ansible_port=2202 ansible_user=vagrant ansible_ssh_private_key_file=/home/ifpb/.vagrant.d/insecure_private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Grupo que unifica todos para o playbook do NTP e Hardening:
[servidores:children]
arq
banco_dados
aplicacao
clientes
