---
- name: Configuração de NTP e Timezone
  hosts: servidores
  become: yes
  tasks:
    - name: Garantir que o fuso horário seja America/Recife
      community.general.timezone:
        name: America/Recife

    - name: Instalar o pacote Chrony
      apt:
        name: chrony
        state: present
        update_cache: yes

    - name: Garantir que o serviço Chrony esteja rodando e habilitado
      service:
        name: chrony
        state: started
        enabled: yes
