---
- name: Configuração do Servidor DHCP no Arq
  hosts: arq
  become: yes
  tasks:
    - name: Instalar o servidor DHCP (isc-dhcp-server)
      apt:
        name: isc-dhcp-server
        state: present
        update_cache: yes

    - name: Configurar a interface de rede do DHCP (eth1)
      lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv4='
        line: 'INTERFACESv4="eth1"'

    - name: Definir a configuração do dhcpd.conf
      blockinfile:
        path: /etc/dhcp/dhcpd.conf
        block: |
          option domain-name "projeto.local";
          option domain-name-servers 192.168.56.112;

          default-lease-time 600;
          max-lease-time 7200;

          authoritative;

          subnet 192.168.56.0 netmask 255.255.255.0 {
            range 192.168.56.150 192.168.56.200;
            option routers 192.168.56.112;
            option broadcast-address 192.168.56.255;
          }

          # Reserva de IP para o Banco de Dados (Exemplo)
          host db {
            hardware ethernet 08:00:27:12:12:20; # Verifique o MAC no seu ip a anterior
            fixed-address 192.168.56.120;
          }

    - name: Reiniciar o serviço DHCP para aplicar as mudanças
      service:
        name: isc-dhcp-server
        state: restarted
        enabled: yes
