---
- name: Configuração do Servidor NFS
  hosts: arq
  become: yes
  tasks:
    - name: Instalar o servidor NFS
      apt:
        name: nfs-kernel-server
        state: present

    - name: Configurar as exportações (Exports) - Sobrescrevendo limpo
      copy:
        dest: /etc/exports
        content: "/mnt *(rw,sync,no_subtree_check,no_root_squash,insecure)\n"

    - name: Aplicar as exportações
      command: exportfs -ra

    - name: Garantir que o serviço NFS está rodando
      service:
        name: nfs-kernel-server
        state: restarted
        enabled: yes

- name: Configuração dos Clientes NFS
  hosts: db, app, cli
  become: yes
  tasks:
    - name: Instalar cliente NFS
      apt:
        name: nfs-common
        state: present

    - name: Criar diretório de montagem nos clientes
      file:
        path: /mnt/dados_compartilhados
        state: directory
        mode: '0777'

    - name: Montar o diretório compartilhado do Arq
      mount:
        path: /mnt/dados_compartilhados
        src: "192.168.56.112:/mnt"
        fstype: nfs
        opts: rw,sync  # <-- Removido o 'insecure' daqui
        state: mounted
